version: "3.1"

language: "en"

pipeline:
- name: "SpacyNLP"
  model: "en_core_web_md"
- name: "SpacyTokenizer"
- name: "spell_checker_component.SpellCheckerComponent"
- name: "SpacyFeaturizer"
- name: "DIETClassifier"
  epochs: 100
  constrain_similarities: true
- name: "EntitySynonymMapper"
- name: "ResponseSelector"
  epochs: 100
  constrain_similarities: true
- name: "FallbackClassifier"
  threshold: 0.6

policies:
- name: "MemoizationPolicy"
- name: "RulePolicy"
- name: "TEDPolicy"
  max_history: 5
  epochs: 100
- name: "UnexpecTEDIntentPolicy"
  max_history: 5
  epochs: 100
assistant_id: 20250510-171755-binary-barnacles
